name: Admission Report Action

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
  
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          cp -r ./fonts/ /usr/share/fonts/my_fonts/
          chmod -R 777 /usr/share/fonts/my_fonts
          fc-cache -fv
          sudo timedatectl set-timezone "Asia/Shanghai"
          timedatectl status
          chmod -R 777 ./driver
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script
        env:
          NJU_USERNAME: ${{ secrets.username }}
          NJU_PASSWORD: ${{ secrets.password }}
          NAME: ${{ secrets.name }}
          PHONE: ${{ secrets.phone }}
          SKM_TOKEN: ${{ secrets.skm_token }}
        run: |
          python run.py
